### ISSUE TITLE
Review / adjust the figures, particularly: superiors and fractions

### ISSUE THREAD

**Issue by aherstowski** [benhoepner/National-Park#16]

**Comment by aherstowski** [comment]
@vv-monsalve getting closer with the numbers and fractions I followed the tutorials (very helpful) the last part of the Fractions... does Google want me to change the Glyphs default code to the attached Tai L code? or leave the code as created by Glyphs...

<img width="893" alt="Screen Shot 2023-06-25 at 8 18 14 AM" src="https://github.com/benhoepner/National-Park/assets/54384906/9b19754e-64d9-40ae-b324-adb462445766">

**Comment by vv-monsalve** [comment]
> does Google want me to change the Glyphs default code to the attached Tai L code? or leave the code as created by Glyphs...

Tal Leming's code would be ideal, for the fractions more complete work. The tutorial mentions a mekkablue script to add it. Otherwise please just ensure of creating all the required glyphs and I'll check the code addition afterward.

**Comment by aherstowski** [comment]
^ @vv-monsalve sorry not sure how to reply in the thread... Super I saw the mekkablue script. I ran it. Happy you can check it. :) thank you!
