### ISSUE TITLE
Switching Shapes in Glyphs (Glyphs 3)

### ISSUE THREAD

**Issue by aherstowski** [benhoepner/National-Park#19]
https://glyphsapp.com/learn/switching-shapes

I have tried both ways that are suggested 
1) Alternate Layers
2) Alternate Glyphs 

I am definitely missing a key part because I can't get either to work. Have just a simple file with just the cent glyph (option 4 if testing in Adobe) is there someone who can help me sort out what I am doing wrong? *Also which one Google recommends Alt Layers or Alt Glyphs.

file can be found in the sources folder.

THANKS!!!!

@vv-monsalve

**Comment by vv-monsalve** [comment]
> Have just a simple file with just the cent glyph

This simplified source file was not working to produce the font. I've modified the `Dollar` sign in the main source file adding the Alternate layers, and you can use it as a reference to add them to the other glyphs.

The test source file lacked the starting value for the Alternate layers to operate. I set it to 600 (Semibold), but feel free to test the font and adjust it to your preference, such as changing it to 700.

Just a quick reminder to merge the open PR #20  before proceeding with any further work on the font.

**Comment by aherstowski** [comment]
@vv-monsalve as always thank you for all the help (the examples) and ALL the critical feedback I really appreciated it!
