### ISSUE TITLE
Build is currently broken

### ISSUE THREAD

**Issue by felipesanches** [benhoepner/National-Park#2]
This seems to be some sort of bug on [glyphsLib](https://github.com/googlefonts/glyphsLib):
https://github.com/benhoepner/National-Park/runs/2843262498?check_suite_focus=true

![Screenshot from 2021-06-16 18-35-38](https://user-images.githubusercontent.com/213676/122297232-aa904380-ced1-11eb-8455-6c236848e48a.png)

**Comment by moyogo** [comment]
This is a Glyphs3 file:
```
.appVersion = "3058";
.formatVersion = 3;
```

**Comment by felipesanches** [comment]
OK.

@simoncozens has been working on adding Glyphs version 3 support to glyphsLib but that was not merged yet. We will try changing the setup in this repo to install glyphsLib from Simon's experimental branch. As it is new code, it may contain bugs, but that can be a good opportunity to test it "in the wild" :-)

**Comment by felipesanches** [comment]
hmmm...

![Screenshot from 2021-06-16 19-40-38](https://user-images.githubusercontent.com/213676/122303970-d19f4300-ceda-11eb-8f8e-556de63d6f99.png)

**Comment by felipesanches** [comment]
I loosened the version requirement for fontmake and now glyphsLib with experimental GlyphsApp version 3 support is installed.

The build still breaks, but now for a different reason:
![Screenshot from 2021-06-16 20-09-51](https://user-images.githubusercontent.com/213676/122306470-e8479900-cede-11eb-9d82-b26a224e8519.png)

and also:
![Screenshot from 2021-06-16 20-10-15](https://user-images.githubusercontent.com/213676/122306484-ef6ea700-cede-11eb-8faf-6bd89b5d3e82.png)

(https://github.com/benhoepner/National-Park/pull/3/checks?check_run_id=2843940563)

@simoncozens, do you think this is a bug in your glyphs 3 support? Or is it actually caused by bad settings in the National-Park project files? **Note:** Most weights being placed in the same 400 coordinate (which is what is usually used only for the Regular) while the Light weight being at negative 100.

**Comment by simoncozens** [comment]
It was a bug in the glyphs3 branch. Should be fixed now.

**Comment by simoncozens** [comment]
OK, so now the code is right, but the build won't work because my glyphs3 branch didn't have the right upstream *tags*, and glyphsLib generates its version based on the git tags. Since it only had old tags, it was advertising itself as an old version which was incompatible with fontmake. *sigh*

Anyway, please change the git source of the glyphsLib 3 experimental branch from `glyphs3-try3` to just `glyphs3`. This is rebased onto main glyphsLib and is a cleaner version of the same code. This branch should have the right tags, and the build will work... apart from the open contour issue which you'll discover when you try it. :-)

**Comment by felipesanches** [comment]
OK, here's what we got now.
Indeed, as seen on the automated build on PR #5, it halts with an "open contour"-related exception. @simoncozens, could you please elaborate on what this is about? Is it a shortcoming of your new glyphs3 code, or is it an actual problem in the font files?

![Screenshot from 2021-06-28 12-17-47](https://user-images.githubusercontent.com/213676/123661798-39bf2480-d80b-11eb-8676-e7b963694362.png)

![Screenshot from 2021-06-28 12-18-27](https://user-images.githubusercontent.com/213676/123661834-40e63280-d80b-11eb-8edf-f90ce0ccf34b.png)

![Screenshot from 2021-06-28 12-18-56](https://user-images.githubusercontent.com/213676/123661861-46dc1380-d80b-11eb-8b3c-b9dcdfdf9bcd.png)

**Comment by simoncozens** [comment]
Well, it's more of a Glyphs 3 feature we don't support yet.

The hyphen is expressed as a two-point open curve and uses the new Glyphs 3 stroke and fill features, which glyphsLib knows nothing about. I don't intend to support stroke/fill any time soon, so the solution is to right-click on the path and choose "Expand outline" to turn it into a proper curve.

**Comment by felipesanches** [comment]
OK. I will merge PR #5 now and then I'll talk to @benhoepner about that

**Comment by felipesanches** [comment]
OK, the build is finally fixed ;-)

**Comment by davelab6** [comment]
Regarding the glyphs3 issues with fontmake, I would recommend - now that its clear how to make the build work - to go back a step and proceed with the "preferred form of modification" during the "design phase", without addressing those issues to work around incomplete glyphs3 support in fontmake - and then return to this only at the end stage of the project, when you then "switch gears" and create separate "build sources" that "branch off" from the "design sources" and optimize the file for building using fontmake, documenting the steps as you go. Then, in future releases, as the design sources evolve, you can repeat the branching off process and do regression testing. 

A prominent libre font project that does this is DJR's Bungee: https://github.com/djrrb/Bungee/tree/master/sources
