### ISSUE TITLE
Design critique

### ISSUE THREAD

**Issue by yanone** [benhoepner/National-Park#4]
Dave Crossland asked me to review the typeface’s design, so I'm posting it here. I looked through the PDFs in the repo.

The lettershapes are lively and wonky, exactly like they should be in a router typeface. So in my opinion, there’s not much to say about the shapes, except for two letters: the lowercase `f` and `t`. Why so narrow? Since the original signs appear to be in all caps, you have no historic reference to draw their shape from. While the typeface makes a surprisingly even appearance otherwise, those two really stick out, better in the heavier, worse in the lighter weights. I suggest to give the shapes space to exist. If you do, go over the `j` and `y` as well. Their appendices are too scared to even peek out.

Otherwise, all the issues in the typeface lie in spacing and finally kerning (apply in that order!). If it was well spaced, it could make for a surprisingly ledgible text face.

Generally, I find the spacing too tight. This appears to be a cultural difference between Europe and the US for display typefaces, but I can't find this narrow spacing when I look at the signage photos. The letters there appear well spaced on the wooden signs, and I vouch for implementing that in the typeface. Ultimately, with such tight spacing, you restrict the typeface’s modern usage to display, forbidding a pleasant text reading experience. So my below remarks assume that the typeface will be optimized for text, as that's the common denominator and doesn't forbid display applications.

Spacing requires a little experience to get right. Do that before you apply any kerning, as kerning tends to counter-balance shortcomings in spacing.

Here’s how I do it:
Balance `n` and `o` as well as `H` and `O` first, by typing out the following lines:
`nnnonnnooonnn` and `HHHOHHHOOOHHH`. Always squinting your eyes (some use the blur feature of Glyphs’ preview pane), first the straight letters (`n` and `H`) need to be balanced against each other to show a smooth rhythm, then the straight letters with the `o`s, and the `o`s against each other. Typing each letter next to each other multiple times as shown greatly enhances the judgement of balanced spacing. Then repeat for all other letters, exchanging only the `o`s and keeping `n` and `H` in place as a "fence". The line `nnnannnaaannn` set in the Bold master will quickly show you how this is effective. The `a` has a rather noticeable spacing issue on both sides and the line shows me how the `n` is too narrow and the `a` is too wide. So in the fence text example, you look at:

1. Spacing of the single target glyph against the `n` fence
2. Spacing of the triple target glyphs against each other. Balance 1) and 2) out, always looking at both the single target glyph and the triple ones
3. If they can't be balanced, as a third step apply kerning between the triple target glyphs. For well spaced typefaces, this should rarely be necessary, but there are exceptions where it must be done. Very pointy letters such as `v` come to mind, or the double-storey `g`.

Before:
<img width="686" alt="Bildschirmfoto 2021-06-25 um 15 39 10" src="https://user-images.githubusercontent.com/175386/123433266-8b796c00-d5cb-11eb-8766-de4a6020e6fb.png">

My shot (took like 10 seconds):
<img width="686" alt="Bildschirmfoto 2021-06-25 um 15 42 56" src="https://user-images.githubusercontent.com/175386/123433690-05a9f080-d5cc-11eb-8743-5a5476a873a4.png">

Generally, the idea of balanced spacing is that counters and outer sidebearings of a letter are in a balance. This means tighter spacing for fatter letters (less counter space), wider spacing for lighter letters (more counter space). 

Router typeface are known to have wonky shapes, but there’s no historic or technical reason for wonky spacing, such as typewriter typefaces understandably have. Routers can even break into previous letter outlines, so even overlaps are conceptually accurate, though not desirable.

Finally, apply kerning. Read the kerning tutorials on the Glyphs website regarding kerning groups, if you haven't already. But  do concentrate on spacing first. It's quite possible to reduce the number of necessary kerning pairs to a bare minumum, in other words, solve a word like the below `avoid` through pure spacing.

<img width="373" alt="Bildschirmfoto 2021-06-25 um 15 56 25" src="https://user-images.githubusercontent.com/175386/123435486-e8762180-d5cd-11eb-9ded-a7600b30c336.png">

**Comment by benhoepner** [comment]
Thanks so much for the feedback—it's greatly appreciated at this early stage of the process. Will definitely be loosening up and evening out the spacing before moving further.

Your comment regarding the width of `f` and `t` is actually one of our bigger concerns with the design at the moment. While we have no reference for those letters routed on physical signage, we do have the [original router file](https://github.com/benhoepner/National-Park/tree/master/presentations-process/router-file-reference), which includes skeletons of the lowercase. These two letters have come up as particularly problematic as we make decisions about how faithful we want to remain to the source and what point we begin making corrections. It sounds like `f` and `t` (and related glyphs) warrant a bit of straying from the reference, so the next version will take that into account.

**Comment by davelab6** [comment]
> my below remarks assume that the typeface will be optimized for text, as that's the common denominator and doesn't forbid display applications.

+1 from me

Generally in the last ~30 years, typefaces have been made as 'single optical size' designs that are scaled linearly to any point size of use; and when choosing from pre-digital (or pre-phototype) typefaces that had a variety of size specific designs, a 'text size' design  (eg 9-12pt) was chosen. 

Therefore the typical spacing is looser, suitable for text, and professional designers have been widely taught to use negative letter-spacing / tracking-in, to tighten up text in headlines. However, this is often taught in a rote way, so its less common that designers track-out fonts that are too tightly spaced for smaller sizes.

**Comment by kalapi** [comment]
Hello @benhoepner and @aherstowski,

It was great to meet you today to discuss your project. I'm attaching the annotated PDF here for your reference. Let me know if you have any questions. 

All the very best – Kalapi
[National_Park_review_scan.pdf](https://github.com/benhoepner/National-Park/files/6862528/National_Park_review_scan.pdf)

**Comment by jeremyshellhorn** [comment]
.

**Comment by vv-monsalve** [comment]
> Generally, I find the spacing too tight.

This is still valid, especially for the ExtraLight master. Followed up on #22
