### ISSUE TITLE
Current status revision

### ISSUE THREAD

**Issue by vv-monsalve** [benhoepner/National-Park#8]
Current project status in the upstream repo [https://github.com/benhoepner/National-Park](https://github.com/benhoepner/National-Park) at commit  `9af5fb5`. Bringing here Rosalie's comments from email + adding answers:

> 1. Glyphsets
> Kernel is a glyphset for multiscripts font that don’t want to support much Latin. The actual minimal set we are requiring is Latin Core: https://github.com/googlefonts/glyphsets/blob/main/GF_glyphsets/Latin/txt/nice-names/GF_Latin_Core.txt.
> 
> Your font has a well developed glyph set, I would recommend to make sure you support:
> - Latin Core (missing three glyphs)
> - Latin Vietnamese (done)
> 
> I strongly recommend to also support Latin Plus.
> 
> Find attached a .plist file containing all GF Latin glyph sets. Add it in the same folder as your .glyphs files, and they will show in the « Filters » section when re-opening the file.
> 
> Globally, your figures are not set up correctly. I would recommend to read these tuto: 
> - https://glyphsapp.com/learn/fractions
> - https://glyphsapp.com/learn/figure-sets
> 
> Your math signs are supposed to have the same width (same as the tabular figures preferably).

First of all, I would like to highlight the impressive progression of the project and the incredible work done :)

While I see the point about suggesting meeting the Latin Plus encoding, given the academic background of the project, I would suggest publishing it with the Latin Core now and leaving the Plus inclusion for a further upgrade.

**Comment by vv-monsalve** [comment]
> 2. Axes
> 
> I see 2 families:
> - Normal
> - Stencil
> 
> The « mind the gap » source, should be treated as additional masters in the stencil font to be able to create a variable axis out of it. If you don’t want to merge the files, you can use the « import font » parameter in font info, it is supposed to link the masters from the two sources to ensure outline compatibility whilst avoiding high number of masters in the source file. Seeing that you have a ExtraLight and Medium master, maybe you can try to interpolate the light master to see if you can get rid of it to reduce file size.

I also see only two families: Normal and Stencil. I'm under the impression the `National-Park_MindtheGap.glyphs` file was only an intermediate production file, but perhaps I'm getting it wrong. @aherstowski could you confirm the purpose of that source file.

Indeed, a Regular instance could be interpolated and then used as a master to reduce the number of masters to be maintained and the file size.

**Comment by vv-monsalve** [comment]
> 3. Onboarding
> 
> It looks like the « stencil » (or « gap »)  axis are still at the very beginning (only four letters), so I wonder why the plan was to onboard the families in Q3. 
> 
> This is more a question for Dave and Tobias;
> Shall we onboard the Normal and Stencil fonts with only a weight axis, and then upgrade them with the « stencil » axis? Or shall we wait for the entire family to be ready (and register the custom axis) to onboard them?

From the above comment, I would say we could move forward with the Normal and Stencil fonts. However, let's wait for Andrea's confirmation about the third source file.

**Comment by vv-monsalve** [comment]
**4. Building the fonts**

I've noticed the `build` GHA has been [failing](https://github.com/benhoepner/National-Park/runs/7031421909?check_suite_focus=true#step:5:17) and the fonts included on the repo seem to be directly exported from Glyphs app. 

I received the same error when trying to build the fonts locally with the command `gftools builder config.yaml`, but couldn't figure out what is causing it.

@simoncozens could you provide context on this?

**Comment by vv-monsalve** [comment]
Summarizing the steps needed:

- [ ] Confirmation of the purpose of the third source file to decide on the need for a custom axis for the project.
- [ ] Please provide more detailed information in the README file. You could read about this file in our [documentation](https://googlefonts.github.io/gf-guide/readmefile.html).
- [ ] Include build instructions in the README file
- [ ] Include a sample image in the README file
- [ ] Either adjust or remove the [trademark file](https://googlefonts.github.io/gf-guide/requirements.html#trademarks). 
- [ ] Solving the problem of GHA `build` to build and test the sources and recover CI capabilities.
- [ ] Add the three missing glyphs to comply with GF Latin Core
- [ ] fsType should be set to zero ("Installable" in Glyphs app options)
- [ ] Addition of copyright and license string in source files
- [ ] Review vertical metrics to meet GF standards

Please focus on the first items of the list, I could take care of the last three points once we have solved the build issue.

**Comment by simoncozens** [comment]
I think the problem is that we temporarily added a line to `requirements.txt` because we were using glyphs3 before that was officially supported, and we did it in a weird way that is no longer supported. Remove the first line of requirements.txt and it should start working again.

**Comment by vv-monsalve** [comment]
> Remove the first line of requirements.txt and it should start working again.

I had that suspicion and created a venv and installed the requirements with that line removed, and got the same result. I'll run it again, in any case, to confirm and let you know. Thanks

**Comment by vv-monsalve** [comment]
The `make build` is reporting:
```
make: yq: Command not found
make: Nothing to be done for `build'.
```
I'm producing the fonts using the command `gftools builder config.yaml` under a venv for the time being.

**Comment by vv-monsalve** [comment]
Notes after today's meeting with @aherstowski 

- We'll proceed with the Latin Core for first publishing and leave the Latin Plus for a later update.
- A Regular master would be added to delete the Liagt and Medium and work only with three; extreme ones + Regular.
- Families and stages:
    - The main standard version will be published first
        - Remaining steps are listed in #12 and #13
    - The Stencil version onboarding will follow
    - Tentatively, a Stencil axis could be added later to the Stencil version to modify the stencil gap. Currently only tested on the `MindtheGap` source file.
- Building process will be tested after merging #11

**Comment by vv-monsalve** [comment]
@simoncozens, the proof process is failing, reporting the [error](https://github.com/benhoepner/National-Park/actions/runs/5739162498/job/15554186511#step:7:27): 

````
*** [Makefile:36: proof] Error 2. 
Error: Process completed with exit code 2.
````

At first, I wondered if it could be cause the `fonts/ttf` dir is not included in the repository. Although, if I understand it correctly, this is optional. What could be missing here?

**Comment by simoncozens** [comment]
As a general tip, when you read an error message, it's always a good idea to look at everything from the *last thing that worked* onwards. The real problem is almost never in the last line of the log, because by that time everything has already gone wrong.

If we look a little bit further here, we can see:

```
gftools: error: unrecognized arguments: proof
```

And that makes me remember that we moved the `proof` command to diffenator2. You need to update your project template using `make update-project-template` (and then check in the changes).

**Comment by vv-monsalve** [comment]
I reviewed the trace and saw indeed the line containing the word "proof", but some static fonts were listed thereafter, which is why I mistakenly assumed the issue was with the fonts since the `diffenator2` also has a `proof` option. This, in turn, led me to overlook the `gftools gen-html test` line above after activating the virtual environment. 

> And that makes me remember that we moved the `proof` command to diffenator2. You need to update your project template using `make update-project-template` (and then check in the changes).

We'll do so. Thanks.

**Comment by vv-monsalve** [comment]
After running `make update-project-template` the following error is reported:

````
npx update-template https://github.com/googlefonts/googlefonts-project-template/
make: npx: No such file or directory
make: *** [update-project-template] Error 1
````

Is it a dependency that should be installed separately (`pip install npx`)? Should it be added to the requirements file?

**Comment by vv-monsalve** [comment]
> Otherwise I can just do the update for you and send you a PR.

I can brew-install it, thank you. However, when you say a PR, do you mean you would be adding it to the requirements file? Or what else would you be modifying? Would any other user of the template need to brew install node?

I'm interested in ensuring this would be available for any user.

**Comment by simoncozens** [comment]
You only need node when you are performing the `update-project-template` step. The update brings any changes to the base project files such as `requirements.txt` and `Makefile` which have been made in `googlefonts-project-template` into your project; for example, in this case we changed the `Makefile` in the `googlefonts-project-template` so that it calls diffenator2 instead of `gftools gen-html`, so you need to bring that change into your local project.

**Comment by vv-monsalve** [comment]
> The update brings any changes to the base project files such as `requirements.txt` and `Makefile` which have been made in `googlefonts-project-template` into your project;

This is clear as the goal of the update.

> You only need node when you are performing the `update-project-template` step.

My question aims to clarify what is needed for any user who would like to update the template in the future. In this case, should we add the installation of node as a required step in the template's [README](https://github.com/googlefonts/googlefonts-project-template#setting-up-your-font) file?

**Comment by simoncozens** [comment]
Good idea, yes. Any maintainer using this upgrade step will need to have node installed. I'll add an issue to the template.

**Comment by vv-monsalve** [comment]
Great! Ty. Now, when brew installing it's requiring to change the ownership of some directories by running extra commands that require sudo log in. Should we warn the users about that possibility? 

````
You should change the ownership of these directories to your user.
  sudo chown -R $(whoami) /usr/local/share/man/man8

And make sure that your user has write permission.
  chmod u+w /usr/local/share/man/man8
````

**Comment by vv-monsalve** [comment]
@aherstowski I've done a [PR updating the template](https://github.com/benhoepner/National-Park/pull/24) now

**Comment by vv-monsalve** [comment]
@simoncozens I've added the above comment to the Template's issue. So I'm closing this issue here.
